[package]
name = "typelisp"
version = "0.1.0"
edition = "2024"
authors = ["Botta <botta@jonil.dev>"]
description = "A typed Lisp/Scheme dialect with custom x86_64 backend and optimizer"
license = "MIT"
repository = "https://github.com/JoNil-Botta/typelisp"

[profile.release]
lto = true
codegen-units = 1
